/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedMyBookingsRouteImport } from './routes/_protected.my-bookings'
import { Route as ProtectedMyPaymentsRouteImport } from './routes/_protected.my-payments'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected.settings'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as BookingShowtimeIdRouteImport } from './routes/booking.$showtimeId'
import { Route as BookingCancelRouteImport } from './routes/booking.cancel'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as MoviesMovieIdRouteImport } from './routes/movies.$movieId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyBookingsRoute = ProtectedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMyPaymentsRoute = ProtectedMyPaymentsRouteImport.update({
  id: '/my-payments',
  path: '/my-payments',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const BookingShowtimeIdRoute = BookingShowtimeIdRouteImport.update({
  id: '/booking/$showtimeId',
  path: '/booking/$showtimeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCancelRoute = BookingCancelRouteImport.update({
  id: '/booking/cancel',
  path: '/booking/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking/success',
  path: '/booking/success',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesMovieIdRoute = MoviesMovieIdRouteImport.update({
  id: '/movies/$movieId',
  path: '/movies/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/my-bookings': typeof ProtectedMyBookingsRoute
  '/my-payments': typeof ProtectedMyPaymentsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/login': typeof PublicLoginRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/booking/cancel': typeof BookingCancelRoute
  '/booking/success': typeof BookingSuccessRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/my-bookings': typeof ProtectedMyBookingsRoute
  '/my-payments': typeof ProtectedMyPaymentsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/login': typeof PublicLoginRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/booking/cancel': typeof BookingCancelRoute
  '/booking/success': typeof BookingSuccessRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/verify-email': typeof VerifyEmailRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/my-bookings': typeof ProtectedMyBookingsRoute
  '/_protected/my-payments': typeof ProtectedMyPaymentsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_public/login': typeof PublicLoginRoute
  '/booking/$showtimeId': typeof BookingShowtimeIdRoute
  '/booking/cancel': typeof BookingCancelRoute
  '/booking/success': typeof BookingSuccessRoute
  '/movies/$movieId': typeof MoviesMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/verify-email'
    | '/dashboard'
    | '/my-bookings'
    | '/my-payments'
    | '/settings'
    | '/login'
    | '/booking/$showtimeId'
    | '/booking/cancel'
    | '/booking/success'
    | '/movies/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/verify-email'
    | '/dashboard'
    | '/my-bookings'
    | '/my-payments'
    | '/settings'
    | '/login'
    | '/booking/$showtimeId'
    | '/booking/cancel'
    | '/booking/success'
    | '/movies/$movieId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_public'
    | '/verify-email'
    | '/_protected/dashboard'
    | '/_protected/my-bookings'
    | '/_protected/my-payments'
    | '/_protected/settings'
    | '/_public/login'
    | '/booking/$showtimeId'
    | '/booking/cancel'
    | '/booking/success'
    | '/movies/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  VerifyEmailRoute: typeof VerifyEmailRoute
  BookingShowtimeIdRoute: typeof BookingShowtimeIdRoute
  BookingCancelRoute: typeof BookingCancelRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  MoviesMovieIdRoute: typeof MoviesMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-bookings': {
      id: '/_protected/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof ProtectedMyBookingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/my-payments': {
      id: '/_protected/my-payments'
      path: '/my-payments'
      fullPath: '/my-payments'
      preLoaderRoute: typeof ProtectedMyPaymentsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/booking/$showtimeId': {
      id: '/booking/$showtimeId'
      path: '/booking/$showtimeId'
      fullPath: '/booking/$showtimeId'
      preLoaderRoute: typeof BookingShowtimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/cancel': {
      id: '/booking/cancel'
      path: '/booking/cancel'
      fullPath: '/booking/cancel'
      preLoaderRoute: typeof BookingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/booking/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/$movieId': {
      id: '/movies/$movieId'
      path: '/movies/$movieId'
      fullPath: '/movies/$movieId'
      preLoaderRoute: typeof MoviesMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMyBookingsRoute: typeof ProtectedMyBookingsRoute
  ProtectedMyPaymentsRoute: typeof ProtectedMyPaymentsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMyBookingsRoute: ProtectedMyBookingsRoute,
  ProtectedMyPaymentsRoute: ProtectedMyPaymentsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  VerifyEmailRoute: VerifyEmailRoute,
  BookingShowtimeIdRoute: BookingShowtimeIdRoute,
  BookingCancelRoute: BookingCancelRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  MoviesMovieIdRoute: MoviesMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
